# Generated by Django 3.1.5 on 2021-01-31 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shareddriver', '0002_auto_20210129_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='ride',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ride',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
