# Generated by Django 3.1.5 on 2021-01-31 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareddriver', '0003_auto_20210131_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='states',
            new_name='status',
        ),
    ]
