# Generated by Django 3.1.5 on 2021-02-04 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shareddriver', '0004_auto_20210131_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='user',
        ),
        migrations.AddField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='shareddriver.user'),
        ),
        migrations.AddField(
            model_name='ride',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='shareddriver.user'),
        ),
    ]
