# Generated by Django 3.1.5 on 2021-02-05 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shareddriver', '0005_auto_20210204_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='data',
            new_name='date',
        ),
    ]
