# Generated by Django 3.1.5 on 2021-02-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareddriver', '0006_auto_20210205_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='sharer',
            field=models.ManyToManyField(blank=True, related_name='sharer', to='shareddriver.User'),
        ),
        migrations.AddField(
            model_name='ride',
            name='vehicle_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ride',
            name='num_of_passenger',
            field=models.IntegerField(default=0),
        ),
    ]
