# Generated by Django 3.1.5 on 2021-02-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shareddriver', '0007_auto_20210209_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
